development:
  adapter: sqlite3
  encoding: utf8
  dbfile: db/mostre_dev.db

test:
  adapter: sqlite3
  encoding: utf8
  dbfile: db/mostre_test.db

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: mostre_prod
  pool: 5
  username: polo
  password: ********
  host: database_host

