development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mostre
  pool: 5000
  username: root
  password:
  host: localhost
  socket: /usr/local/Cellar/mysql/5.6.19/mysqld.sock

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
