# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dd215093592ff7a311fa046736e4c7c7b9eb6ae3ba0721281c92e818531e55decf35e12f751d57d4391eef45654a906ddbc47292f118e6e3d8cfb13c9d7432b

test:
  secret_key_base: 8bf95be263558d0abc68390bfadf2e2dedecc848c4e2464afd5fa2f6d2486471ef5d4934335bce3e76b12fa936bbe4ca05e99aad0f00bd8fa4b7018e5ac82e9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
